sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    password: ""
  wechat:
    appid: wxe4be8c42c6747832
    secret: a08d976130e49ddf8b390db119658400
